baseURL = 'https://shawnyeager.github.io/nostr-ux-research/'
languageCode = 'en-us'
title = 'Design Patterns for Nostr UX'
theme = 'hextra'

# Mount existing content
[module]
  [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "patterns"
    target = "content/docs/patterns"

  [[module.mounts]]
    source = "appendices"
    target = "content/docs/resources"

  [[module.mounts]]
    source = "static"
    target = "static"

[params]
  description = 'Design patterns for building consumer Nostr applications with great UX'

  # Plausible.io analytics
  [params.analytics.plausible]
    domain = "shawnyeager.github.io"

  [params.navbar]
    displayTitle = true
    displayLogo = true
    width = "wide"

    [params.navbar.logo]
      path = "images/logo.svg"
      dark = "images/logo-dark.svg"
      link = "/"
      width = 32
      height = 32

  [params.footer]
    displayCopyright = true
    displayPoweredBy = false

[[menu.main]]
  name = "Documentation"
  pageRef = "/docs"
  weight = 1

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/shawnyeager/nostr-ux-research"
  weight = 6
  [menu.main.params]
    icon = "github"

[markup]
  [markup.highlight]
    style = 'github'
    lineNos = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ['HTML']
  page = ['HTML']
  section = ['HTML', 'RSS']
